repos:
-   repo: local
    hooks:
    -   id: check-whitespace
        name: check whitespace
        entry: git diff --check
        language: system
        
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
