kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: solyx-dev
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  # Grafana
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  # Prometheus
  - containerPort: 30002
    hostPort: 30002
    protocol: TCP
